title: Jungsun Yoo
# logo: /assets/img/JY Profile.jpeg
# logo: /assets/img/JY Profile2.JPG
# logo: /assets/img/JY Profile 4.JPG
logo: /assets/img/JY Profile 8.JPG
description: she/her/hers
[Google Scholar](https://scholar.google.com/citations?hl=en&user=RfaVfPcAAAAJ)
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
