title: Jungsun Yoo
# logo: /assets/img/JY Profile.jpeg
# logo: /assets/img/JY Profile2.JPG
logo: /assets/img/JY Profile 4.JPG
description: she/her/hers
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
