title: Jungsun Yoo, Ph.D. 
# logo: /assets/img/JY Profile.jpeg
# logo: /assets/img/JY Profile2.JPG
# logo: /assets/img/JY Profile 4.JPG
logo: /assets/img/JY Profile 9.JPG
description: jungsun.yoo@princeton.edu
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
